# -*- coding: utf-8 -*-
"""Deon Thomas Binny_2548519_LAB1_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozaMB7oRJc_NRxEIlkz92OERWhNQhDCx
"""

import numpy as np

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [1],
              [1],
              [0]], dtype=float)

model = Sequential([
    Dense(4, input_dim=2, activation='tanh'),
    Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer=Adam(learning_rate=0.1),
    metrics=['accuracy']
)

model.fit(X, y, epochs=1000, verbose=0)

predictions = model.predict(X)

print("Keras XOR Predictions:")
print(np.round(predictions))

import torch
import torch.nn as nn
import torch.optim as optim

# XOR Dataset
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])

y = torch.tensor([[0.],
                  [1.],
                  [1.],
                  [0.]])

# Define MLP Model
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.hidden = nn.Linear(2, 4)
        self.output = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.tanh(self.hidden(x))
        x = torch.sigmoid(self.output(x))
        return x

model = XORNet()

# Loss and Optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

# Train Model
for epoch in range(1000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

# Predict
with torch.no_grad():
    predictions = model(X)
    print("PyTorch XOR Predictions:")
    print(torch.round(predictions))

import tensorflow as tf

# XOR Dataset
X = tf.constant([[0.,0.],
                 [0.,1.],
                 [1.,0.],
                 [1.,1.]])

y = tf.constant([[0.],
                 [1.],
                 [1.],
                 [0.]])

# Initialize Weights
W1 = tf.Variable(tf.random.normal([2, 4]))
b1 = tf.Variable(tf.zeros([4]))

W2 = tf.Variable(tf.random.normal([4, 1]))
b2 = tf.Variable(tf.zeros([1]))

# Define Model
def mlp(x):
    hidden = tf.tanh(tf.matmul(x, W1) + b1)
    output = tf.sigmoid(tf.matmul(hidden, W2) + b2)
    return output

# Loss Function
def loss_fn(y_true, y_pred):
    return tf.reduce_mean(
        tf.keras.losses.binary_crossentropy(y_true, y_pred)
    )

# Optimizer
optimizer = tf.optimizers.Adam(learning_rate=0.1)

# Train Model
for epoch in range(1000):
    with tf.GradientTape() as tape:
        preds = mlp(X)
        loss = loss_fn(y, preds)
    grads = tape.gradient(loss, [W1, b1, W2, b2])
    optimizer.apply_gradients(zip(grads, [W1, b1, W2, b2]))

# Predict
print("TensorFlow Low-Level XOR Predictions:")
print(tf.round(mlp(X)))

